name: Check JSON files are sensible

on:
  pull_request:
    branches: [main]

jobs:
  check-orphans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check JSON files
        run: bash .github/workflows/check-json.sh

