name: Onboarding - Request to be added as a contributor
description: Request for your organisation to be added to this repository
title: "[Onboarding Request]: "
labels: ["onboarding-request"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out your organisation's details and representative's details below:

  - type: input
    id: organisation-name
    attributes:
      label: Organisation Name
      description: The name of your organisation
      placeholder: e.g. Obsidian Systems
    validations:
      required: true

  - type: dropdown
    id: organisation-type
    attributes:
      label: Organisation Type
      description: Organisation Type
      options:
        - Audit
        - Package Development
    validations:
      required: true

  - type: input
    id: github-username
    attributes:
      label: Representative's GitHub username
      description:  (without the @ symbol)
      placeholder: e.g. octocat
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Once a maintainer reviews your request, they will decide whether you will be added as a contributor
